// @flow

export type DriverData = {
    AbbrevName: string,
    CarClassColor: number,
    CarClassID: number,
    CarClassLicenseLevel: number,
    CarClassMaxFuelPct: string,
    CarClassRelSpeed: number,
    CarClassShortName: string,
    CarClassWeightPenalty: string,
    CarDesignStr: string,
    CarID: number,
    CarIdx: number,
    CarIsAI: number,
    CarIsPaceCar: number,
    CarNumber: number,
    CarNumberDesignStr: string,
    CarNumberRaw: number,
    CarPath: string,
    CarScreenName: string,
    CarScreenNameShort: string,
    CarSponsor_1: number,
    CarSponsor_2: number,
    CurDriverIncidentCount: number,
    HelmetDesignStr: string,
    IRating: number,
    Initials: string,
    IsSpectator: number,
    LicColor: number,
    LicLevel: number,
    LicString: string,
    LicSubLevel: number,
    SuitDesignStr: string,
    TeamID: number,
    TeamIncidentCount: number,
    TeamName: string,
    UserID: number,
    UserName: string,
};

export type DriverInfoData = {
    DriverCarEngCylinderCount: number,
    DriverCarEstLapTime: number,
    DriverCarFuelKgPerLtr: number,
    DriverCarFuelMaxLtr: number,
    DriverCarIdleRPM: number,
    DriverCarIdx: number,
    DriverCarMaxFuelPct: number,
    DriverCarRedLine: number,
    DriverCarSLBlinkRPM: number,
    DriverCarSLFirstRPM: number,
    DriverCarSLLastRPM: number,
    DriverCarSLShiftRPM: number,
    DriverHeadPosX: number,
    DriverHeadPosY: number,
    DriverHeadPosZ: number,
    DriverIncidentCount: number,
    DriverPitTrkPct: number,
    DriverSetupIsModified: number,
    DriverSetupLoadTypeName: string,
    DriverSetupName: string,
    DriverSetupPassedTech: number,
    DriverUserID: number,
    Drivers: DriverData[],
    PaceCarIdx: number,
};
